CREATE DATABASE IF NOT EXISTS wap_system;
USE wap_system;

CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id VARCHAR(50) NOT NULL UNIQUE,
    student_email VARCHAR(255) NOT NULL UNIQUE,
    student_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id VARCHAR(50) NOT NULL UNIQUE,
    admin_email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE room (
    id INT AUTO_INCREMENT PRIMARY KEY,
    room_name VARCHAR(255) NOT NULL UNIQUE,
    `block` VARCHAR(50) NOT NULL,
    floor VARCHAR(50) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    capacity VARCHAR(255) NOT NULL,
    amenities VARCHAR(255) NOT NULL,
    `status` VARCHAR(50) NOT NULL
);

